name: Deploy and Update Wiki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."

  update-wiki:
    uses: ./.github/workflows/update-wiki.yaml
    with:
      section: "Home Component"
      env: "dev"
