name: Update Wiki After Merge

on:
  workflow_call:
    inputs:
      section:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki Repository
        run: |
          git clone "https://github.com/hannguyenkms/test-workflow-wiki.wiki.git" wiki

      - name: Update Deployment Record in the Correct Section
        run: |
          cd wiki
          FILE="Home.md"
          
          # Map short section input (app/infra) to full section title
          case "${{ inputs.section }}" in
            app)
              SECTION="Home Component"
              ;;
            infra)
              SECTION="Home Component Infra"
              ;;
            *)
              echo "Invalid section input: ${{ inputs.section }} (allowed: app, infra)"
              exit 1
              ;;
          esac

          # Populate deployment details
          ENV="${{ inputs.env }}"
          BRANCH="${GITHUB_REF_NAME}"
          DATE="$(date '+%Y-%m-%d %H:%M:%S')"
          STATUS="✅ Success"
          WORKFLOW_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          
          # Replace the existing row for this ENV within the correct section
          # Limit sed operation to lines between the section header and the next section
          sed -i "/^# ${SECTION}$/,/^# / s~^| *\`${ENV}\`.*\$~| \`${ENV}\` | \`${BRANCH}\` | ${DATE} | ${STATUS} | [Workflow URL](${WORKFLOW_URL}) |~" "$FILE"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd wiki
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .

          # Commit only if there are actual changes
          if git diff --cached --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Update deployment record for ${ENV} in ${SECTION}"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.wiki.git
            git push
          fi
