name: Update Wiki After Merge

on:
  workflow_call:
    inputs:
      section:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki
        run: |
          git clone "https://github.com/hannguyenkms/test-workflow-wiki.wiki.git" wiki

      - name: Append Deployment Record to Correct Section
        run: |
          cd wiki
          FILE="Home.md"
          
          SECTION="${{ inputs.section }}"
          ENV="${{ inputs.env }}"
          BRANCH="${GITHUB_REF_NAME}"
          DATE="$(date '+%Y-%m-%d %H:%M:%S')"
          STATUS="✅ Success"
          WORKFLOW_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          
          # Create new row for the table
          NEW_ROW="| \`${ENV}\` | \`${BRANCH}\` | ${DATE} | ${STATUS} | [Workflow URL](${WORKFLOW_URL}) |"
          
          # Override the deployment record if it already exists
          # This will replace the existing row for the same environment
          awk -v section="## ${SECTION}" -v env="| \`${ENV}\` |" -v row="$NEW_ROW" '
            $0==section {
              print; getline; print; getline; print; in_section=1; updated=0; next
            }
            in_section && $0 ~ env {
              if (!updated) {print row; updated=1}
              next
            }
            in_section && $0 ~ /^## / {
              if (!updated) {print row; updated=1}
              in_section=0
            }
            {
              print
            }
            END {
              if (in_section && !updated) print row
            }
          ' "$FILE" > tmp && mv tmp "$FILE"

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd wiki
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Append deployment record to ${SECTION}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.wiki.git
          git push
